//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/controllers/player_controller.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Player_controller: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Player_controller()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""player_controller"",
    ""maps"": [
        {
            ""name"": ""keyboard"",
            ""id"": ""d792d8fe-d3b5-405d-8aa2-aaa904696ce2"",
            ""actions"": [
                {
                    ""name"": ""a"",
                    ""type"": ""Button"",
                    ""id"": ""2ab3413e-0679-4792-8c82-a53e06133473"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""b"",
                    ""type"": ""Button"",
                    ""id"": ""8cad02a9-ddb3-41dc-a67c-d8fab48089f8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""c"",
                    ""type"": ""Button"",
                    ""id"": ""e4cf0d86-4113-45ec-b2cf-1a1d08f5bb87"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""d"",
                    ""type"": ""Button"",
                    ""id"": ""2f79ab18-95c1-4d09-bc0f-0b6b44dffc52"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""e"",
                    ""type"": ""Button"",
                    ""id"": ""bbe76d68-c4ae-46ec-81e7-295717e1a2c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""f"",
                    ""type"": ""Button"",
                    ""id"": ""94ec8d75-ba75-47fe-9d33-e887e7d064de"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""g"",
                    ""type"": ""Button"",
                    ""id"": ""01685d38-8b12-4fe4-9fb9-340b3b6ae1d2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""h"",
                    ""type"": ""Button"",
                    ""id"": ""3f6550a0-bea1-4018-a69f-d7ef8d800f37"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""i"",
                    ""type"": ""Button"",
                    ""id"": ""6b529ba8-593e-45de-b680-9cf49e3a06d6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""j"",
                    ""type"": ""Button"",
                    ""id"": ""cdd2cee0-5f21-48d0-b044-29d0d6b8c761"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""k"",
                    ""type"": ""Button"",
                    ""id"": ""099fea3c-8f57-4303-b8fe-71eb71710874"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""l"",
                    ""type"": ""Button"",
                    ""id"": ""b9281854-0e0b-4484-81a4-c4d83ca7ed7c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""m"",
                    ""type"": ""Button"",
                    ""id"": ""f0827472-17dd-410b-8b62-72f39186203a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""n"",
                    ""type"": ""Button"",
                    ""id"": ""fc42e3bb-f935-4303-80c7-d9216900c38c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""o"",
                    ""type"": ""Button"",
                    ""id"": ""a59820cb-47dc-4ed2-ac66-77bf9c3ce544"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""p"",
                    ""type"": ""Button"",
                    ""id"": ""a8cafccf-3dbe-4b44-8b7a-53c36e52901e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""q"",
                    ""type"": ""Button"",
                    ""id"": ""cc56815e-57ca-40f6-9d84-ec3321ca0844"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""r"",
                    ""type"": ""Button"",
                    ""id"": ""fd9de5cc-f3fb-4d0b-b8aa-b954f1be4fce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""s"",
                    ""type"": ""Button"",
                    ""id"": ""bc9c0620-6452-4582-88fa-5562ed0726c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""t"",
                    ""type"": ""Button"",
                    ""id"": ""c3066bf6-30d8-480d-972c-b08daa6934e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""u"",
                    ""type"": ""Button"",
                    ""id"": ""9cf1802a-b1a8-4852-a52e-dfec2af79cd7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""v"",
                    ""type"": ""Button"",
                    ""id"": ""cccc2428-9733-4463-bbcd-c3b0cf2c6bfd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""w"",
                    ""type"": ""Button"",
                    ""id"": ""216a8cdc-93e0-4c96-80f2-89f13a641395"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""x"",
                    ""type"": ""Button"",
                    ""id"": ""4b2ed8b5-bc86-41dd-a5dd-16fa8eb63531"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""y"",
                    ""type"": ""Button"",
                    ""id"": ""0b00448a-0cdb-4323-a9f8-e1146d971e81"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""z"",
                    ""type"": ""Button"",
                    ""id"": ""6a2b2010-0e82-4a10-a119-7aacee8e9b9b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""99e5c5ea-4caa-4bf2-9e17-d16509748142"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""c"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb222838-ff60-4ea0-b866-9564a8adb877"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""d"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d27aae2f-c430-422b-a627-1ca6f295a338"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""a"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95542345-ce6b-4bcd-affe-5394bb928ad4"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""b"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fc456b71-b0c7-4200-9b9d-107a6874e00e"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""e"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3924a9a9-9802-47c0-b5f2-919b0d28683f"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""f"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b0cbbf49-6073-487b-ad52-22cd1ad34494"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""g"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3847567-5660-4915-9b73-1f5fe7814b00"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""h"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29d53ed4-33c8-4298-8662-25c7038e4921"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""i"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed5b631f-e627-41ff-a5ce-1bbb269b202b"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""j"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f87999c8-bfd7-48a3-abac-d05984e49573"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""k"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d2e4d79-19b9-4b14-abd7-80ba4f9cd5b8"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""l"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32c21f74-12c3-4ee3-99a4-25a73701b8b2"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""m"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e4a7276e-a083-4b40-b226-3c198552ae86"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""n"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc13262d-46e6-4363-8087-cbf2f6e33884"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""o"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aa436924-4e09-4a15-8a72-033f7e6a62d0"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""p"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cfae780a-b94f-4208-851a-efa81d98dd64"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""q"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6422b878-8a69-4afb-b70a-a3651a7a66d0"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""r"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5f9a9e4-4890-4ca5-8282-08a899e62b31"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""s"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd76bfab-c626-423e-aae8-0b83dd22d146"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""t"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62e6c9ff-500c-4073-bc83-d4bb7316f427"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""u"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f3a7ecb-28b9-40ac-a31b-435078bb8c57"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""v"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64363112-cc9a-49a7-bd19-1029c07372c0"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""w"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f613a607-2bdc-4df8-a767-67885f2728be"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""x"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab23877e-9e3f-45a9-a41a-932770f52298"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""y"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""043aec63-ba6d-46f7-9c49-f5cbdd777a34"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""z"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""mouse"",
            ""id"": ""b86b5ddc-9ffe-4cf0-8c85-f86b32cb7a8a"",
            ""actions"": [
                {
                    ""name"": ""leftClick"",
                    ""type"": ""Button"",
                    ""id"": ""e9e3daa5-79c0-4263-9d8b-fc9b028060b3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""rightClick"",
                    ""type"": ""Button"",
                    ""id"": ""76ee8954-d4f1-4d76-9a51-3f8fdea2bd27"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""27cbc41b-909e-4338-bfcc-8383691ccf9f"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""leftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c67dd53c-abda-43a0-a392-94f982adb4cc"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // keyboard
        m_keyboard = asset.FindActionMap("keyboard", throwIfNotFound: true);
        m_keyboard_a = m_keyboard.FindAction("a", throwIfNotFound: true);
        m_keyboard_b = m_keyboard.FindAction("b", throwIfNotFound: true);
        m_keyboard_c = m_keyboard.FindAction("c", throwIfNotFound: true);
        m_keyboard_d = m_keyboard.FindAction("d", throwIfNotFound: true);
        m_keyboard_e = m_keyboard.FindAction("e", throwIfNotFound: true);
        m_keyboard_f = m_keyboard.FindAction("f", throwIfNotFound: true);
        m_keyboard_g = m_keyboard.FindAction("g", throwIfNotFound: true);
        m_keyboard_h = m_keyboard.FindAction("h", throwIfNotFound: true);
        m_keyboard_i = m_keyboard.FindAction("i", throwIfNotFound: true);
        m_keyboard_j = m_keyboard.FindAction("j", throwIfNotFound: true);
        m_keyboard_k = m_keyboard.FindAction("k", throwIfNotFound: true);
        m_keyboard_l = m_keyboard.FindAction("l", throwIfNotFound: true);
        m_keyboard_m = m_keyboard.FindAction("m", throwIfNotFound: true);
        m_keyboard_n = m_keyboard.FindAction("n", throwIfNotFound: true);
        m_keyboard_o = m_keyboard.FindAction("o", throwIfNotFound: true);
        m_keyboard_p = m_keyboard.FindAction("p", throwIfNotFound: true);
        m_keyboard_q = m_keyboard.FindAction("q", throwIfNotFound: true);
        m_keyboard_r = m_keyboard.FindAction("r", throwIfNotFound: true);
        m_keyboard_s = m_keyboard.FindAction("s", throwIfNotFound: true);
        m_keyboard_t = m_keyboard.FindAction("t", throwIfNotFound: true);
        m_keyboard_u = m_keyboard.FindAction("u", throwIfNotFound: true);
        m_keyboard_v = m_keyboard.FindAction("v", throwIfNotFound: true);
        m_keyboard_w = m_keyboard.FindAction("w", throwIfNotFound: true);
        m_keyboard_x = m_keyboard.FindAction("x", throwIfNotFound: true);
        m_keyboard_y = m_keyboard.FindAction("y", throwIfNotFound: true);
        m_keyboard_z = m_keyboard.FindAction("z", throwIfNotFound: true);
        // mouse
        m_mouse = asset.FindActionMap("mouse", throwIfNotFound: true);
        m_mouse_leftClick = m_mouse.FindAction("leftClick", throwIfNotFound: true);
        m_mouse_rightClick = m_mouse.FindAction("rightClick", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // keyboard
    private readonly InputActionMap m_keyboard;
    private List<IKeyboardActions> m_KeyboardActionsCallbackInterfaces = new List<IKeyboardActions>();
    private readonly InputAction m_keyboard_a;
    private readonly InputAction m_keyboard_b;
    private readonly InputAction m_keyboard_c;
    private readonly InputAction m_keyboard_d;
    private readonly InputAction m_keyboard_e;
    private readonly InputAction m_keyboard_f;
    private readonly InputAction m_keyboard_g;
    private readonly InputAction m_keyboard_h;
    private readonly InputAction m_keyboard_i;
    private readonly InputAction m_keyboard_j;
    private readonly InputAction m_keyboard_k;
    private readonly InputAction m_keyboard_l;
    private readonly InputAction m_keyboard_m;
    private readonly InputAction m_keyboard_n;
    private readonly InputAction m_keyboard_o;
    private readonly InputAction m_keyboard_p;
    private readonly InputAction m_keyboard_q;
    private readonly InputAction m_keyboard_r;
    private readonly InputAction m_keyboard_s;
    private readonly InputAction m_keyboard_t;
    private readonly InputAction m_keyboard_u;
    private readonly InputAction m_keyboard_v;
    private readonly InputAction m_keyboard_w;
    private readonly InputAction m_keyboard_x;
    private readonly InputAction m_keyboard_y;
    private readonly InputAction m_keyboard_z;
    public struct KeyboardActions
    {
        private @Player_controller m_Wrapper;
        public KeyboardActions(@Player_controller wrapper) { m_Wrapper = wrapper; }
        public InputAction @a => m_Wrapper.m_keyboard_a;
        public InputAction @b => m_Wrapper.m_keyboard_b;
        public InputAction @c => m_Wrapper.m_keyboard_c;
        public InputAction @d => m_Wrapper.m_keyboard_d;
        public InputAction @e => m_Wrapper.m_keyboard_e;
        public InputAction @f => m_Wrapper.m_keyboard_f;
        public InputAction @g => m_Wrapper.m_keyboard_g;
        public InputAction @h => m_Wrapper.m_keyboard_h;
        public InputAction @i => m_Wrapper.m_keyboard_i;
        public InputAction @j => m_Wrapper.m_keyboard_j;
        public InputAction @k => m_Wrapper.m_keyboard_k;
        public InputAction @l => m_Wrapper.m_keyboard_l;
        public InputAction @m => m_Wrapper.m_keyboard_m;
        public InputAction @n => m_Wrapper.m_keyboard_n;
        public InputAction @o => m_Wrapper.m_keyboard_o;
        public InputAction @p => m_Wrapper.m_keyboard_p;
        public InputAction @q => m_Wrapper.m_keyboard_q;
        public InputAction @r => m_Wrapper.m_keyboard_r;
        public InputAction @s => m_Wrapper.m_keyboard_s;
        public InputAction @t => m_Wrapper.m_keyboard_t;
        public InputAction @u => m_Wrapper.m_keyboard_u;
        public InputAction @v => m_Wrapper.m_keyboard_v;
        public InputAction @w => m_Wrapper.m_keyboard_w;
        public InputAction @x => m_Wrapper.m_keyboard_x;
        public InputAction @y => m_Wrapper.m_keyboard_y;
        public InputAction @z => m_Wrapper.m_keyboard_z;
        public InputActionMap Get() { return m_Wrapper.m_keyboard; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KeyboardActions set) { return set.Get(); }
        public void AddCallbacks(IKeyboardActions instance)
        {
            if (instance == null || m_Wrapper.m_KeyboardActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_KeyboardActionsCallbackInterfaces.Add(instance);
            @a.started += instance.OnA;
            @a.performed += instance.OnA;
            @a.canceled += instance.OnA;
            @b.started += instance.OnB;
            @b.performed += instance.OnB;
            @b.canceled += instance.OnB;
            @c.started += instance.OnC;
            @c.performed += instance.OnC;
            @c.canceled += instance.OnC;
            @d.started += instance.OnD;
            @d.performed += instance.OnD;
            @d.canceled += instance.OnD;
            @e.started += instance.OnE;
            @e.performed += instance.OnE;
            @e.canceled += instance.OnE;
            @f.started += instance.OnF;
            @f.performed += instance.OnF;
            @f.canceled += instance.OnF;
            @g.started += instance.OnG;
            @g.performed += instance.OnG;
            @g.canceled += instance.OnG;
            @h.started += instance.OnH;
            @h.performed += instance.OnH;
            @h.canceled += instance.OnH;
            @i.started += instance.OnI;
            @i.performed += instance.OnI;
            @i.canceled += instance.OnI;
            @j.started += instance.OnJ;
            @j.performed += instance.OnJ;
            @j.canceled += instance.OnJ;
            @k.started += instance.OnK;
            @k.performed += instance.OnK;
            @k.canceled += instance.OnK;
            @l.started += instance.OnL;
            @l.performed += instance.OnL;
            @l.canceled += instance.OnL;
            @m.started += instance.OnM;
            @m.performed += instance.OnM;
            @m.canceled += instance.OnM;
            @n.started += instance.OnN;
            @n.performed += instance.OnN;
            @n.canceled += instance.OnN;
            @o.started += instance.OnO;
            @o.performed += instance.OnO;
            @o.canceled += instance.OnO;
            @p.started += instance.OnP;
            @p.performed += instance.OnP;
            @p.canceled += instance.OnP;
            @q.started += instance.OnQ;
            @q.performed += instance.OnQ;
            @q.canceled += instance.OnQ;
            @r.started += instance.OnR;
            @r.performed += instance.OnR;
            @r.canceled += instance.OnR;
            @s.started += instance.OnS;
            @s.performed += instance.OnS;
            @s.canceled += instance.OnS;
            @t.started += instance.OnT;
            @t.performed += instance.OnT;
            @t.canceled += instance.OnT;
            @u.started += instance.OnU;
            @u.performed += instance.OnU;
            @u.canceled += instance.OnU;
            @v.started += instance.OnV;
            @v.performed += instance.OnV;
            @v.canceled += instance.OnV;
            @w.started += instance.OnW;
            @w.performed += instance.OnW;
            @w.canceled += instance.OnW;
            @x.started += instance.OnX;
            @x.performed += instance.OnX;
            @x.canceled += instance.OnX;
            @y.started += instance.OnY;
            @y.performed += instance.OnY;
            @y.canceled += instance.OnY;
            @z.started += instance.OnZ;
            @z.performed += instance.OnZ;
            @z.canceled += instance.OnZ;
        }

        private void UnregisterCallbacks(IKeyboardActions instance)
        {
            @a.started -= instance.OnA;
            @a.performed -= instance.OnA;
            @a.canceled -= instance.OnA;
            @b.started -= instance.OnB;
            @b.performed -= instance.OnB;
            @b.canceled -= instance.OnB;
            @c.started -= instance.OnC;
            @c.performed -= instance.OnC;
            @c.canceled -= instance.OnC;
            @d.started -= instance.OnD;
            @d.performed -= instance.OnD;
            @d.canceled -= instance.OnD;
            @e.started -= instance.OnE;
            @e.performed -= instance.OnE;
            @e.canceled -= instance.OnE;
            @f.started -= instance.OnF;
            @f.performed -= instance.OnF;
            @f.canceled -= instance.OnF;
            @g.started -= instance.OnG;
            @g.performed -= instance.OnG;
            @g.canceled -= instance.OnG;
            @h.started -= instance.OnH;
            @h.performed -= instance.OnH;
            @h.canceled -= instance.OnH;
            @i.started -= instance.OnI;
            @i.performed -= instance.OnI;
            @i.canceled -= instance.OnI;
            @j.started -= instance.OnJ;
            @j.performed -= instance.OnJ;
            @j.canceled -= instance.OnJ;
            @k.started -= instance.OnK;
            @k.performed -= instance.OnK;
            @k.canceled -= instance.OnK;
            @l.started -= instance.OnL;
            @l.performed -= instance.OnL;
            @l.canceled -= instance.OnL;
            @m.started -= instance.OnM;
            @m.performed -= instance.OnM;
            @m.canceled -= instance.OnM;
            @n.started -= instance.OnN;
            @n.performed -= instance.OnN;
            @n.canceled -= instance.OnN;
            @o.started -= instance.OnO;
            @o.performed -= instance.OnO;
            @o.canceled -= instance.OnO;
            @p.started -= instance.OnP;
            @p.performed -= instance.OnP;
            @p.canceled -= instance.OnP;
            @q.started -= instance.OnQ;
            @q.performed -= instance.OnQ;
            @q.canceled -= instance.OnQ;
            @r.started -= instance.OnR;
            @r.performed -= instance.OnR;
            @r.canceled -= instance.OnR;
            @s.started -= instance.OnS;
            @s.performed -= instance.OnS;
            @s.canceled -= instance.OnS;
            @t.started -= instance.OnT;
            @t.performed -= instance.OnT;
            @t.canceled -= instance.OnT;
            @u.started -= instance.OnU;
            @u.performed -= instance.OnU;
            @u.canceled -= instance.OnU;
            @v.started -= instance.OnV;
            @v.performed -= instance.OnV;
            @v.canceled -= instance.OnV;
            @w.started -= instance.OnW;
            @w.performed -= instance.OnW;
            @w.canceled -= instance.OnW;
            @x.started -= instance.OnX;
            @x.performed -= instance.OnX;
            @x.canceled -= instance.OnX;
            @y.started -= instance.OnY;
            @y.performed -= instance.OnY;
            @y.canceled -= instance.OnY;
            @z.started -= instance.OnZ;
            @z.performed -= instance.OnZ;
            @z.canceled -= instance.OnZ;
        }

        public void RemoveCallbacks(IKeyboardActions instance)
        {
            if (m_Wrapper.m_KeyboardActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IKeyboardActions instance)
        {
            foreach (var item in m_Wrapper.m_KeyboardActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_KeyboardActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public KeyboardActions @keyboard => new KeyboardActions(this);

    // mouse
    private readonly InputActionMap m_mouse;
    private List<IMouseActions> m_MouseActionsCallbackInterfaces = new List<IMouseActions>();
    private readonly InputAction m_mouse_leftClick;
    private readonly InputAction m_mouse_rightClick;
    public struct MouseActions
    {
        private @Player_controller m_Wrapper;
        public MouseActions(@Player_controller wrapper) { m_Wrapper = wrapper; }
        public InputAction @leftClick => m_Wrapper.m_mouse_leftClick;
        public InputAction @rightClick => m_Wrapper.m_mouse_rightClick;
        public InputActionMap Get() { return m_Wrapper.m_mouse; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MouseActions set) { return set.Get(); }
        public void AddCallbacks(IMouseActions instance)
        {
            if (instance == null || m_Wrapper.m_MouseActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MouseActionsCallbackInterfaces.Add(instance);
            @leftClick.started += instance.OnLeftClick;
            @leftClick.performed += instance.OnLeftClick;
            @leftClick.canceled += instance.OnLeftClick;
            @rightClick.started += instance.OnRightClick;
            @rightClick.performed += instance.OnRightClick;
            @rightClick.canceled += instance.OnRightClick;
        }

        private void UnregisterCallbacks(IMouseActions instance)
        {
            @leftClick.started -= instance.OnLeftClick;
            @leftClick.performed -= instance.OnLeftClick;
            @leftClick.canceled -= instance.OnLeftClick;
            @rightClick.started -= instance.OnRightClick;
            @rightClick.performed -= instance.OnRightClick;
            @rightClick.canceled -= instance.OnRightClick;
        }

        public void RemoveCallbacks(IMouseActions instance)
        {
            if (m_Wrapper.m_MouseActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMouseActions instance)
        {
            foreach (var item in m_Wrapper.m_MouseActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MouseActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MouseActions @mouse => new MouseActions(this);
    public interface IKeyboardActions
    {
        void OnA(InputAction.CallbackContext context);
        void OnB(InputAction.CallbackContext context);
        void OnC(InputAction.CallbackContext context);
        void OnD(InputAction.CallbackContext context);
        void OnE(InputAction.CallbackContext context);
        void OnF(InputAction.CallbackContext context);
        void OnG(InputAction.CallbackContext context);
        void OnH(InputAction.CallbackContext context);
        void OnI(InputAction.CallbackContext context);
        void OnJ(InputAction.CallbackContext context);
        void OnK(InputAction.CallbackContext context);
        void OnL(InputAction.CallbackContext context);
        void OnM(InputAction.CallbackContext context);
        void OnN(InputAction.CallbackContext context);
        void OnO(InputAction.CallbackContext context);
        void OnP(InputAction.CallbackContext context);
        void OnQ(InputAction.CallbackContext context);
        void OnR(InputAction.CallbackContext context);
        void OnS(InputAction.CallbackContext context);
        void OnT(InputAction.CallbackContext context);
        void OnU(InputAction.CallbackContext context);
        void OnV(InputAction.CallbackContext context);
        void OnW(InputAction.CallbackContext context);
        void OnX(InputAction.CallbackContext context);
        void OnY(InputAction.CallbackContext context);
        void OnZ(InputAction.CallbackContext context);
    }
    public interface IMouseActions
    {
        void OnLeftClick(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
    }
}
